sudo: false
language: scala
scala:
  - 2.11.7
branches:
  except:
    - settings
before_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
